common: &common
  adapter: postgresql
  encoding: unicode
  username: gymleader
  password:
  pool: 5

development:
  <<: *common
  database: gymleader_development

test:
  <<: *common
  database: gymleader_test

production:
  <<: *common
  database: gymleader
