common: &common
  adapter: postgresql
  encoding: unicode
  username: crossfit
  password:
  pool: 5

development:
  <<: *common
  database: crossfit_development

test:
  <<: *common
  database: crossfit_test

production:
  <<: *common
  database: crossfit_production
